@startuml mobileorder
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho
left to right direction

entity "users" as users {
  user_id
  --
  email
  role
  created_at
  updated_at
}

entity "orders" as orders {
  order_id
  --
  user_id<<FK>>
  shop_id <<FK>>
  order_date
  total_amount
  guest_order_token
  status
  created_at
  updated_at
}

entity "order_product" as order_product {
  order_product_id
  --
  order_id<<FK>>
  product_id<<FK>>
  quantity
  price_at_order
  created_at
  updated_at
}

entity "products" as products {
  product_id
  --
  product_name
  description
  price
  is_available
  created_at
  updated_at
}

entity "shop_product" as shop_product {
  shop_product_id
  --
  product_id<<FK>>
  shop_id<<FK>>
  created_at
  updated_at
}

entity "shops" as shops {
  shop_id
  --
  name
  description
  location
  is_open
  created_at
  updated_at
}

entity "shop_staff" as shop_staff {
  shop_staff_id
  --
  shop_id<<FK>>
  user_id<<FK>>
  created_at
  updated_at
}

users ||--|| shop_staff
users |o--o{ orders
orders ||--|{ order_product
products ||--o{ order_product
products ||--o{ shop_product
shops ||--o{ shop_product
shops ||--o{ orders
shops ||--|{ shop_staff

@enduml
