services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/local.Dockerfile
    ports:
      - "8080:8080"
    container_name: mobileorder
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app

  db:
    image: postgres:latest
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
