services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/local.Dockerfile
    ports:
      - "8080:8080"
    container_name: mobileorder
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app

  db:
    image: postgres:latest
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "80:8080"
    volumes:
      # swagger.jsonをコンテナ内の一時的なパスにマウントします
      - ./docs/swagger.json:/app/swagger.json
    environment:
      # 一時的なパスを環境変数で指定します
      # これにより、コンテナの起動スクリプトがファイルを適切な場所にコピーします
      - SWAGGER_JSON=/app/swagger.json
    depends_on:
      - app

volumes:
  postgres_data:
