// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "既存のユーザーを認証し、新しい認証トークンを発行します。\nリクエストにゲスト注文トークンを含めることで、既存のゲスト注文をアカウントに紐付けることも可能です。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "認証 (Auth)"
                ],
                "summary": "ログイン (Log In)",
                "parameters": [
                    {
                        "description": "ユーザー情報 (メールアドレスと、任意でゲスト注文トークン)",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AuthenticateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "認証成功。新しい認証トークンを返します。",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストボディが不正です",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "認証に失敗しました (メールアドレスが存在しない等)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "サーバー内部でエラーが発生しました",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "新しいユーザーアカウントを作成し、認証トークンとユーザー情報を返します。\nリクエストにゲスト注文トークンを含めることで、既存のゲスト注文をアカウントに紐付けることも可能です。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "認証 (Auth)"
                ],
                "summary": "新規ユーザー登録 (Sign Up)",
                "parameters": [
                    {
                        "description": "ユーザー情報 (メールアドレスと、任意でゲスト注文トークン)",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AuthenticateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "登録成功。ユーザー情報と認証トークンを返します。",
                        "schema": {
                            "$ref": "#/definitions/models.SignUpResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストボディが不正です",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "指定されたメールアドレスは既に使用されています",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "サーバー内部でエラーが発生しました",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/orders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ログイン中のユーザーの注文履歴をステータスで絞り込んで取得します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "注文 (Order)"
                ],
                "summary": "注文履歴の取得 (Get Order List)",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "cooking",
                                "completed",
                                "handed"
                            ],
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "注文ステータス (Order Status)",
                        "name": "status",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注文履歴のリスト",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.OrderListResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "クエリパラメータが不正です",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "認証に失敗しました",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "サーバー内部でエラーが発生しました",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/orders/{order_id}/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "特定の注文IDの現在のステータスと待ち状況をリアルタイムで取得します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "注文 (Order)"
                ],
                "summary": "注文ステータスの取得 (Get Order Status)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "注文ID (Order ID)",
                        "name": "order_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "現在の注文ステータス",
                        "schema": {
                            "$ref": "#/definitions/models.OrderStatusResponse"
                        }
                    },
                    "400": {
                        "description": "注文IDの形式が不正です",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "認証に失敗しました",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "注文が見つからないか、アクセス権がありません",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "サーバー内部でエラーが発生しました",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/shops/{shop_id}/guest-orders": {
            "post": {
                "description": "未ログインのゲストユーザーとして新しい注文を作成します。認証は不要です。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "注文 (Order)"
                ],
                "summary": "ゲストの注文作成 (Create Order - Guest)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "店舗ID (Shop ID)",
                        "name": "shop_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "注文内容 (Order details)",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "作成された注文IDとゲスト用トークン",
                        "schema": {
                            "$ref": "#/definitions/models.CreateOrderResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストボディまたは店舗IDが不正です",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "サーバー内部でエラーが発生しました",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/shops/{shop_id}/orders": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証済みのユーザーとして新しい注文を作成します。リクエストには有効なBearerトークンが必要です。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "注文 (Order)"
                ],
                "summary": "認証ユーザーの注文作成 (Create Order - Authenticated)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "店舗ID (Shop ID)",
                        "name": "shop_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "注文内容 (Order details)",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "作成された注文ID",
                        "schema": {
                            "$ref": "#/definitions/models.AuthenticatedOrderResponse"
                        }
                    },
                    "400": {
                        "description": "リクエストボディまたは店舗IDが不正です",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "認証に失敗しました",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "サーバー内部でエラーが発生しました",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AuthenticateRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "new.user@example.com"
                },
                "guest_order_token": {
                    "type": "string",
                    "example": "15ff4999-2cfd-41f3-b744-926e7c5c7a0e"
                }
            }
        },
        "models.AuthenticatedOrderResponse": {
            "type": "object",
            "properties": {
                "order_id": {
                    "type": "integer"
                }
            }
        },
        "models.CreateOrderRequest": {
            "type": "object",
            "properties": {
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.OrderProductRequest"
                    }
                }
            }
        },
        "models.CreateOrderResponse": {
            "type": "object",
            "properties": {
                "guest_order_token": {
                    "type": "string",
                    "example": "15ff4999-2cfd-41f3-b744-926e7c5c7a0"
                },
                "message": {
                    "type": "string",
                    "example": "Order created successfully as a guest. Please sign up to claim this order."
                },
                "order_id": {
                    "type": "integer",
                    "example": 6
                }
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNiwicm9sZSI6ImN1c3RvbWVyIiwiZXhwIjoxNzUxNTIwMjk1LCJpYXQiOjE3NTEyNjEwOTV9.oItkz3SDGGK0eQSP6BBq-SF3nWLk7Q-ITD1J6UrXeUE"
                }
            }
        },
        "models.OrderItem": {
            "type": "object",
            "properties": {
                "product_name": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "models.OrderListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.OrderItem"
                    }
                },
                "order_date": {
                    "type": "string"
                },
                "order_id": {
                    "type": "integer"
                },
                "shop_name": {
                    "type": "string"
                },
                "status": {
                    "description": "\"cooking\" or \"completed\"",
                    "type": "string"
                },
                "total_amount": {
                    "type": "number"
                },
                "waiting_count": {
                    "type": "integer"
                }
            }
        },
        "models.OrderProductRequest": {
            "type": "object",
            "properties": {
                "product_id": {
                    "type": "integer",
                    "example": 1
                },
                "quantity": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "models.OrderStatusResponse": {
            "type": "object",
            "properties": {
                "order_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "waiting_count": {
                    "type": "integer"
                }
            }
        },
        "models.SignUpResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNiwicm9sZSI6ImN1c3RvbWVyIiwiZXhwIjoxNzUxNTIwMjk1LCJpYXQiOjE3NTEyNjEwOTV9.oItkz3SDGGK0eQSP6BBq-SF3nWLk7Q-ITD1J6UrXeUE"
                },
                "user": {
                    "$ref": "#/definitions/models.UserResponse"
                }
            }
        },
        "models.UserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "new.user@example.com"
                },
                "role": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer",
                    "example": 16
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "認証トークンを'Bearer 'に続けて入力してください。 (例: Bearer {JWTトークン})",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Mobile Order API",
	Description:      "モバイルオーダー（事前注文・決済）システムのためのAPI仕様書です。\nユーザー認証、商品情報の取得、注文処理などの機能を提供します。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
